### ISSUE TITLE
Reducing heatmap data to 1 row/column causes an hclust error

### ISSUE THREAD

**Issue by shackett** [calico/romic#13]
<img width="607" alt="Screen Shot 2021-07-16 at 2 06 11 PM" src="https://user-images.githubusercontent.com/508404/125990553-d6d98752-2140-4915-a104-9dec1183f2dd.png">

**Comment by zatch3301** [comment]
Can share your code snippet it will be a great help in understanding the problem.

**Comment by shackett** [comment]
Hi @zatch3301, here's a reprex

```r
library(dplyr)

df <- tidyr::crossing(letters = LETTERS, numbers = 1) %>%
         mutate(noise = rnorm(n()))
hclust_order(df, "letters", "numbers", "noise", "both")

```
